// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using YCNRefine.Data;

#nullable disable

namespace YCNRefine.Data.Migrations
{
    [DbContext(typeof(YcnrefineContext))]
    [Migration("20230510091045_Initial-Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("YCNRefine.Core.Entities.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("UserIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Chat__3214EC077D6070AF");

                    b.HasIndex("DatasetId");

                    b.ToTable("Chat", (string)null);
                });

            modelBuilder.Entity("YCNRefine.Core.Entities.Dataset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CreatedByUser")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Dataset__3214EC07087AB91B");

                    b.ToTable("Dataset", (string)null);
                });

            modelBuilder.Entity("YCNRefine.Core.Entities.GenerativeSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Context")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<string>("Input")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Output")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Generati__3214EC07F257DC9E");

                    b.HasIndex("DatasetId");

                    b.ToTable("GenerativeSample", (string)null);
                });

            modelBuilder.Entity("YCNRefine.Core.Entities.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Message__3214EC07B7DF2459");

                    b.HasIndex("ChatId");

                    b.ToTable("Message", (string)null);
                });

            modelBuilder.Entity("YCNRefine.Core.Entities.OriginalSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DatasetId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Original__3214EC073881AC6A");

                    b.HasIndex("DatasetId");

                    b.ToTable("OriginalSource", (string)null);
                });

            modelBuilder.Entity("YCNRefine.Core.Entities.QuestionAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CorrectAnswer")
                        .HasColumnType("bit");

                    b.Property<int>("OriginalSourceId")
                        .HasColumnType("int");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserIdentifier")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id")
                        .HasName("PK__Question__3214EC07A87916FC");

                    b.HasIndex("OriginalSourceId");

                    b.ToTable("QuestionAnswer", (string)null);
                });

            modelBuilder.Entity("YCNRefine.Core.Entities.Chat", b =>
                {
                    b.HasOne("YCNRefine.Core.Entities.Dataset", "Dataset")
                        .WithMany("Chats")
                        .HasForeignKey("DatasetId")
                        .IsRequired()
                        .HasConstraintName("FK_Dataset_Chat");

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("YCNRefine.Core.Entities.GenerativeSample", b =>
                {
                    b.HasOne("YCNRefine.Core.Entities.Dataset", "Dataset")
                        .WithMany("GenerativeSamples")
                        .HasForeignKey("DatasetId")
                        .IsRequired()
                        .HasConstraintName("FK_Dataset_GenerativeSample");

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("YCNRefine.Core.Entities.Message", b =>
                {
                    b.HasOne("YCNRefine.Core.Entities.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("ChatId")
                        .IsRequired()
                        .HasConstraintName("FK_Chat_Message");

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("YCNRefine.Core.Entities.OriginalSource", b =>
                {
                    b.HasOne("YCNRefine.Core.Entities.Dataset", "Dataset")
                        .WithMany("OriginalSources")
                        .HasForeignKey("DatasetId")
                        .IsRequired()
                        .HasConstraintName("FK_Dataset_OriginalSource");

                    b.Navigation("Dataset");
                });

            modelBuilder.Entity("YCNRefine.Core.Entities.QuestionAnswer", b =>
                {
                    b.HasOne("YCNRefine.Core.Entities.OriginalSource", "OriginalSource")
                        .WithMany("QuestionAnswers")
                        .HasForeignKey("OriginalSourceId")
                        .IsRequired()
                        .HasConstraintName("FK_OriginalSource_QuestionAnswer");

                    b.Navigation("OriginalSource");
                });

            modelBuilder.Entity("YCNRefine.Core.Entities.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("YCNRefine.Core.Entities.Dataset", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("GenerativeSamples");

                    b.Navigation("OriginalSources");
                });

            modelBuilder.Entity("YCNRefine.Core.Entities.OriginalSource", b =>
                {
                    b.Navigation("QuestionAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
